### ISSUE TITLE
FR: Cycle through Sidebar panes

### ISSUE THREAD

**Issue by ryanwwest** [phibr0/cycle-through-panes#18]
It would be awesome if this plugin could cycle not only through the main note panes, but also the left and right sidebar panes. See this FR that I made on Obsidian's Discourse: https://forum.obsidian.md/t/go-to-previous-next-sidebar-pane-and-focus-on-pane/57562. However, I don't expect that to be integrated soon so having it here instead (and hopefully being able to reuse a lot of the existing logic) would be awesome!

**Comment by Vinzent03** [comment]
Do I understand you correctly, that you want 4 new commands. 2 for each side to go to the left/right tab inside the sidebar?

**Comment by ryanwwest** [comment]
That's right, I haven't thought of anything more intuitive. 

While the link I added also talks about additional commands to focus on each side pane (no matter which tabis currently active) or the main pane, that's probably outside the scope of this plugin.

**Comment by Vinzent03** [comment]
Well, I don't think an extra command just to change focus on the sidebar is needed. I could implement it that way the switching command can be used to focus on either sidebar and on next call actually switch to left or right.

**Comment by ryanwwest** [comment]
Are you saying if you have a ~`go to next left sidebar tab` command, then the first invocation focuses on the pane, but doesn't actually switch it - and then the second invocation _does_ advance the tab to the right?

That seems a bit confusing to me... but possibly. Do other programs have a similar behavior?

**Comment by ryanwwest** [comment]
I guess another way to do it is use the same, existing next/previous commands for the _main_ tab but have them apply to the active portion of the window. So have some sort of commands to move the focus between the main pane (or if there are multiple main panes open, between each of them), the left sidebar, and the right sidebar, and the next/previous tab commands apply to whatever the focus is currently on.

**Comment by ryanwwest** [comment]
Thanks @FelipeRearden ! This is the same thing that I originally suggested and appears to work well. @Vinzent03 , I still think this FR (or the final variation of it I mentioned that uses the same hotkeys for cycle forwards/reverse in any pane, mains or left/right sidebar) could fit in well in the scope of the plugin and thus provide more value overall than that one. However, it's up to you since there's a good alternative now - just as fine if this is closed because a solution exists.

**Comment by ryanwwest** [comment]
Actually, I just realized that @FelipeRearden opened a very similar varied FR of this on that other plugin: https://github.com/houcheng/obsidian-cycle-in-sidebar-plugin/issues/4, and another regarding moving focus to the sidebar: https://github.com/houcheng/obsidian-cycle-in-sidebar-plugin/issues/5. So he has pretty much my same thought process haha. I realized that you can already use the default Obsidian commands `Focus on tab group above/below/to the left/to the right` to also move _from_ the sidebar focus _into_ the main focus, so we really just need a command to get out (preferably, the Obsidian devs would just let these same commands also move us into sidebar focus).

**Comment by Vinzent03** [comment]
So we need two commands to focus on either sidebar. To cycle in them, we could use the existing ones for the root tabs?

**Comment by ryanwwest** [comment]
Yeah, what if we use the ones you already came up with to focus on whatever pane / sidebar pane is currently focused/active (like https://github.com/houcheng/obsidian-cycle-in-sidebar-plugin/issues/4)? Then the only thing left is a way to focus on left or right sidebar as focusing back on the main panes is already solved.

**Comment by FelipeRearden** [comment]
> So we need two commands to focus on either sidebar. To cycle in them, we could use the existing ones for the root tabs?

Exactly @Vinzent03 !!!! What is missing to close the workflow is two commands:

1️⃣ `focus on left sidebar`
2️⃣ `focus on right sidebar`

Because we already have a way to focus on active note. What we dont have today is a way to focus on the sidebars.

> Yeah, what if we use the ones you already came up with to focus on whatever pane / sidebar pane is currently focused/active (like https://github.com/houcheng/obsidian-cycle-in-sidebar-plugin/issues/4)? Then the only thing left is a way to focus on left or right sidebar as focusing back on the main panes is already solved.

100% agree with @ryanwwest comment :)

**Comment by Vinzent03** [comment]
So do you want to use the commands provided by this plugin to cycle through the panes within the sidebar or the ones by Obsidian itself. Currently, the commands from this plugin only work with the root tabs. The ones from Obsidian itself already work within the sidebar.

**Comment by FelipeRearden** [comment]
> So do you want to use the commands provided by this plugin to cycle through the panes within the sidebar or the ones by Obsidian itself. Currently, the commands from this plugin only work with the root tabs. The ones from Obsidian itself already work within the sidebar.

I have a solid opinion about this new feature but I am gonna wait for the @ryanwwest reply since he is the creator of the FR :)

**Comment by ryanwwest** [comment]
Interesting, `ctrl-tab` seems to work for moving sidepanes forward, but `ctrl-shift-tab` doesn't move them in reverse (though it does for the root/main tabs). I image a future Obsidian update would fix this, but hard to say when. I'm not sure what option is better, interested to hear what @FelipeRearden thinks.

**Comment by FelipeRearden** [comment]
> I'm not sure what option is better, interested to hear what @FelipeRearden thinks.

@Vinzent03 let me share my opinion about this ...

1️⃣ The pain point is that we can NOT cycle through the sidebars using the keyboard.
2️⃣ In my humble opinion doesn't make sense to cycle through PANES + SIDEBARS . We need a way to cycle ONLY through SIDEBARS and ONLY through PANES 

Based on this have have these new features:

💻 New Command `Cycle through Left Sidebar`
💻 New Command `Cycle through Right Sidebar`

🆘 BUT these new commands need to have a special feature !!!!!!!!!!!!
→  While cycle through the sidebars it need to KEEP the focus on the sidebars instead of jump to the active note (`app.commands.executeCommandById('editor:focus')`) every time we cycle inside the sidebar. 

→ in others words we need to `focus on the active sidebar ` while we are performing the cycle command 

--- 

Let me know what you guys think about this and sorry again for step into the conversation 🙏

**Comment by Vinzent03** [comment]
What about using the existing commands for this case. So they cycle within the current split of the window. Meaning, if you are already in a sidebar, it cycles within that. If you are already in the main tabs, everything stays the same.

**Comment by FelipeRearden** [comment]
> What about using the existing commands for this case. So they cycle within the current split of the window. Meaning, if you are already in a sidebar, it cycles within that. If you are already in the main tabs, everything stays the same.

You are a legend @Vinzent03 🥇🥇🥇 spectacular idea to make the commands dynamic !!!! it's the best scenario :)

Please please please make sure that we don't loose the focus that already is in the sidebar while cycle 🙏🙏🙏

>By the way, using `Go to next tab` and  `Go to previous tab` from core Obsidian in the sidebar works great for me. Though, note that I'm on the latest Insider version.

Just to let you know ....

📸 In the latest public release the commands doesn't show in command pallette WHEN the focus is on the sidebar .
![1D6C55D3-4877-4BEF-9B2D-24E48A51DBEC](https://user-images.githubusercontent.com/85180696/233445738-93a49dab-8e3e-4504-b329-f3ed3a298225.jpeg)

**Comment by Vinzent03** [comment]
Should be done now! :tada: There are now two new commands to focus on the sidebar. The option (by default enabled) to stay in the current split.

**Comment by FelipeRearden** [comment]
> Should be done now! 🎉 There are now two new commands to focus on the sidebar. The option (by default enabled) to stay in the current split.

Hello @Vinzent03  and @ryanwwest !!!

I tested the new release and I wanna share some information with you :)

## My Environment 

💻 Obsidian Latest Public Release

⌨️ I tested on Desktop and Mobile (iPad with mouse and keyboard)

📹 Screen record is on iPad but the behavior is the same on Desktop

1️⃣ Left Sidebar with 3 Core Plugins: File Explorer, Tags, Search and Starred 

## Tests

I tested two workflows: 

🅰️ Focus on Left Sidebar → From Active Note to Sidebar (open and/or closed)

🅱️ Cycle Through Panes → Cycle Between Sidebar items: File Explorer, Tags, Search and Starred 

## 🅰️ Focus on Left Sidebar

🐞 I found a issue using the **Search Core Plugin** when the Search is Empty → it is NOT focusing on the search text field when the search is empty

📹 Search Not empty
![video](https://user-images.githubusercontent.com/85180696/233652361-1f380651-2f5a-45d7-a6dd-67db56cd9453.MOV)


📹 Search empty
![video](https://user-images.githubusercontent.com/85180696/233652521-9faecddc-1869-4629-9cdb-4b24dfc1b5fe.MOV)



✅ All good with File Explorer and Tags (Starred doesn't have keyboard navigation)


## 🅱️ Cycle Through Panes → Cycle Between Sidebar items: File Explorer, Tags, Search and Starred 

💻 Settings
![E4CDF7CE-56AE-42E2-98BA-4213A0F6098E](https://user-images.githubusercontent.com/85180696/233653346-ded9d4e4-b1c6-4d6d-a38d-0fb2976c7969.jpeg)

🐞 Some typo is missing in the end :)

🐞 Unfortunately I couldn't **Cycle** between the Items using any of the commands 
→ Cycle Next Tab
→ Cycle Previous Tab
→ Cycle Right Tab
→ Cycle Left Tab

ℹ️ **On Desktop** I got one Cycle from File Explorer to Tags  but nothing more 
ℹ️ **On Mobile** I got nothing

👍Maybe this is an issue because I am on public release and you are on the new Beta ;

👍I hope you could reproduce some items on your end 🙏

--- 

Let me know if you need more tests . I am here to help !

Have a great day !

**Comment by Vinzent03** [comment]
Thanks for the testing! I forgot to mention that you still need to enable the different view types. So basically call for every view type in the sidebar you want to cycle the "Enable this view type" command.
I won't find the time to fix the search focus in the next days. So it will take just a bit more time.

**Comment by FelipeRearden** [comment]
> I won't find the time to fix the search focus in the next days. So it will take just a bit more time.

No problem at all :) Thanks for let me know, I really appreciate :)

> Thanks for the testing! I forgot to mention that you still need to enable the different view types. So basically call for every view type in the sidebar you want to cycle the "Enable this view type" command.

My bad, I should have thought about this before testing !!!!

This way, just to let you know about this feature on Desktop and Mobile

✅ **It's working perfect on DESKTOP** exactly that way that I always wanted to navigate through Sidebars 

🆘  **It's NOT working on MOBILE** unfortunately even after enable these different view types I was not able to cycle between the views on Sidebar . Same behavior when using the mobile emulator on Desktop :(


→ I am talking about the behavior Mobile because I use Obsidian Mobile  on iPadOS with mouse and keyboard as my main device  
→ Just to let you know if you wanna take a look in the future 🙏

---

Lets keep talking @Vinzent03  and thank you very much for everything !!!!!

**Comment by Vinzent03** [comment]
Should be fixed now :tada: Mobile sidebar works a bit differently...

**Comment by FelipeRearden** [comment]
> Should be fixed now 🎉 Mobile sidebar works a bit differently...

Hello @Vinzent03 !!!!

Forgive me for my late reply :)

🅰️ Focus on Search Text Field → Working Perfect on version 1.2.1 - Mobile and Desktop ✅

🅰️ Cycle Through **Sidebar** Panes → Working Perfect on version 1.2.1 - Mobile and Desktop ✅

Thank you very much for the fix 🙏

Running my tests, I found a new bug ONLY ON MOBILE ....

🆘 **The Command `Focus on Left Sidebar` stopped working on version only for Mobile (and Desktop emulator)**

→  **By this I mean 2 things:**

1️⃣ I CANT set the focus **from** the Active Note **to the** Sidebar using the command the same way that I do on version 1.2.0

2️⃣ While I am cycle through the Sidebar, I dont have focus on the Sidebar. When I press the command `Focus on Left Sidebar` after cycle I CANT get focus as well. 


Sorry for bring more problems to you 🙏

I wish you a fantastic day ☀️
