### ISSUE TITLE
Text cursor does not switch when cycling through panes

### ISSUE THREAD

**Issue by AngelusDomini** [phibr0/cycle-through-panes#4]
As title says, when cycling through panes, the text cursor does not cycle along with the panes, specifically in edit mode. When using your plugin to move from Pane A to Pane B, Pane B does get selected—as it should, but the text cursor remains in Pane A. I would have to use my mouse—which the plugin advertised would reduce the usage of in the first place—and manually select Pane B in order to relocate the cursor accordingly; otherwise, I would be typing on Pane A when I intended to type on Pane B, even though the latter is the focused pane. It would be great that switching from Pane A to B with your plugin would also move the text cursor from Pane A to B.

Hoping you would fix this issue and improve this great plugin further. Stay safe!

**Comment by phibr0** [comment]
Working on a fix, as a workaround right now you can press `ctrl + e` twice after switching panes.

**Comment by AngelusDomini** [comment]
Good to know that you're working on it as well as about the workaround 😁

**Comment by pjeby** [comment]
If you don't care about wraparound, you can use the built-in commands to "focus on pane to the left", "focus on pane to the right", "up" and "down".  They don't wrap from first to last, but you can bind them to the same keys and use them in place of this plugin.

**Comment by AngelusDomini** [comment]
> If you don't care about wraparound, you can use the built-in commands to "focus on pane to the left", "focus on pane to the right", "up" and "down". They don't wrap from first to last, but you can bind them to the same keys and use them in place of this plugin.

Doesn't seem to be as convenient for me; I'm not able to cycle through the panes with this workaround which forces me to switch between the two hotkeys whenever I reach the last pane on either side—which makes it a more frequent problem when you usually only have two panes open instead of more.

**Comment by phibr0** [comment]
It seems to be working fine for me..
[Video](https://youtu.be/0bzjfcKWe7I)

**Comment by pjeby** [comment]
I just updated to 0.0.3 and restarted, and while the new commit fixes the focusing issue, it does not seem to support wraparound either.

However, in my case, that's probably due to an Obsidian issue that prevents making a sidebar document active.  (Obsidian allows dragging a document into a sidebar pane, but it doesn't allow making it "active", even though you can click into it and edit it.)  Sidebar documents are included in `iterateLeaves()` and `getLeavesOfType("markdown")`, so this plugin attempts to cycle through them.  But since they cannot be made active, the previously-active leaf remains active, so the cycling stops.

One way to fix that would be for this plugin to skip such leaves when moving forward or backward.  A simple way to do this is to check that the `workspace.activeLeaf` has actually changed after calling `setActiveLeaf()`.  If it hasn't, then the leaf wasn't suitable, and needs to be skipped in the rotation.  This approach should be forward compatible in case Obsidian ever actually allows sidebar leaves to become active.

**Comment by phibr0** [comment]
Seems like this is a another Issue

**Comment by AngelusDomini** [comment]
It works now with the new update (0.0.4). Thanks so much!
